# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=2G" "mode=755" ];
    };

  fileSystems."/home" =
    { device = "pool/ink/home";
      fsType = "zfs";
    };

  fileSystems."/stay" =
    { device = "pool/ink/stay";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "pool/nix";
      fsType = "zfs";
    };

  fileSystems."/etc/nixos" =
    { device = "/stay/etc/nixos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/log" =
    { device = "/stay/var/log";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/901E-5F18";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e7d8357e-1dfd-4ecc-a0ce-26ccf602ce46"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
